### PR TITLE
A test run at breaking async storage out of what is normally shipped.

### PR DESCRIPTION
**Pull request by rmevans9**
This would be a breaking change because it introduces these two things:

1. `useReactNative` no longer takes the configuration for async storage and doesn't turn it on at all
2. The client id is basically nullified and thus users could run into issues with Android simulators duplicating connections.

The changes a user would have to do it their config are:

```diff
import Reactotron from "reactotron-react-native"
+ import useAsyncStorageClientId from "reactotron-react-native/dist/useAsyncStorageClientId"
+ import asyncStoragePlugin from "reactotron-react-native/dist/plugins/asyncStorage"

{...}

Reactotron.configure({
  name: "Demo App",
+  ...useAsyncStorageClientId,
})

Reactotron.useReactNative({
-  asyncStorage: { ignore: ['secret'] }
})

+ Reactotron.use(asyncStoragePlugin({ ignore: ["secret"] }))
```

### CODE REVIEW

**Comment by rmevans9** [comment]
Yeah, right now the documentation for all things reactotron live on the main repo. If I am going to merge this there would have to be a matching PR on that repo to document this change.

I have been going back and forth on pushing the documentation that is specific to each reactotron repo to the repo itself. I am open to suggestion on that front as well.

**Comment by jamonholmgren** [comment]
I am okay with it living on the main repo!

**Comment by rmevans9** [comment]
I've changed directions on this a little bit so that we are not so dependent on specific implementations. This now works with anything that has a `setItem(KEY, VALUE)` and `getItem(KEY)`. This is the change to the configuration users will have to implement:

```
import { AsyncStorage } from 'react-native' // OR import it from the community one
{...}
Reactotron.setAsyncStorageHandler(AsyncStorage)
{...}
Reactotron.useReactNative()
{...}
Reactotron.connect()
```

**Comment by djMax** [comment]
I like the sethandler approach a lot better than the original, so +1 from the peanut gallery.

**Comment by rmevans9** [comment]
@djMax I hardly call a consumer of this library the peanut gallery. Thanks for your input! 

I am thinking that is the direction this is going to go. It will have to be a breaking change so I will need to update some docs and make sure to get this called out when I go to merge this. I will have this all wrapped up before .60 lands in stable 👍

**Comment by jhonlly** [comment]
Hi everyone. I'm trying to use with @react-native-community/async-storage but not working. I use "reactotron-react-native": "3.6.2". How I can use it?

Thanks.

**Comment by rmevans9** [comment]
I need to get this merged then you should be good to go. I will try and work on that this weekend

**Comment by lucaashrq** [comment]
Any update for this issue?

**Comment by rodrigofeijao** [comment]
@rmevans9 Let me know if you need any help on this. would be amazing having this out asap. Apparently there's a bunch of people complaining about it.

**Comment by rmevans9** [comment]
I will be releasing this as a beta version tonight.

**Pull request merged**
